zhuzichu520/FluentUI

.github/workflows/macos.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml

before: example_ubuntu-20.04_6.4.3.AppImage
after: example_v1.1.8_ubuntu-20.04_Qt6.4.3.AppImage

add tag name into workflow release assets

---

.github/workflows/windows-mingw.yml
.github/workflows/windows.yml

Rename windows workflow release for msvc and mingw

Optimize workflow

---

example/main.cpp

Fix crash in macOS.

---

src/FluApp.cpp

SingleInstance状态下的窗口应当要接收到传输的参数，并自动置顶。

Improve SingleInstance.

---

src/imports/FluentUI/Controls/FluTabView.qml

Added ToolTip for FluTabView's tab.

---

src/imports/FluentUI/Controls/FluTableView.qml

Allow the table to set the maximum height of each row based on the content.

---

CMakeLists.txt
example/CMakeLists.txt
src/CMakeLists.txt

让库在macOS以Universal Library的形式编译。

Make the library compile as Universal Library in macOS.

---

src/imports/FluentUI/Controls/FluTableView.qml

Let the pagination can be manually adjusted in FluTableView.

---

src/imports/FluentUI/Controls/FluAcrylic.qml

加入调整整体圆角的功能，同时修复调整模糊化蒙板颜色显示不正确的问题。

Improve FluAcrylic.

---

example/qml/page/T_Home.qml

Fix the blur background in T_Home.qml

Fix the blur background in T_Home.qml

---

example/qml/component/CustomWindow.qml
example/qml/page/T_Home.qml
example/src/main.cpp
src/imports/FluentUI/Controls/FluNavigationView.qml
src/imports/FluentUI/Controls/FluWindow.qml

1. 为窗口加入模糊背景
2. 为 FluNavigationView的minimal模式加入acrylic效果

Improve acrylic effect for example and FluNavigationView.

---

example/src/main.cpp

Fix the system titlebar buttons show behind surface.

---

src/imports/FluentUI/Controls/FluNavigationView.qml

修复FluNavigationView在Compact模式下显示面板颜色是透明的问题

Fix acrylic effect for FluNavigationView CompactAndPanel mode.

---

src/imports/FluentUI/Controls/FluContentDialog.qml
src/imports/FluentUI/Controls/FluPopup.qml

加入FluPopup，方便用于各种场景，而不仅仅局限于FluContentDialog。

Add FluPopup for universally use.

---

src/imports/FluentUI/Controls/FluPopup.qml

Expose more bulr options of FluPopup.

---

example/qml/page/T_Menu.qml

Typo (in T_Menu.qml)

---

src/imports/FluentUI/Controls/FluNavigationView.qml

修复FluNavigationView在push相同url组件的时候没有考虑pageMode的问题。

Fix FluNavigationView push function in Standard mode.

---

src/imports/FluentUI/Controls/FluTableView.qml

Make the FluTableView readonly text copiable.

---

CMakeLists.txt
example/CMakeLists.txt
src/CMakeLists.txt

Add Build static lib option and fix the bug of static lib build.

---

example/CMakeLists.txt
example/src/main.cpp

Fix the bug of static resources didn't imported by engine.

---

example/CMakeLists.txt
example/example.qrc
example/qml/App.qml
example/qml/global/ItemsOriginal.qml
example/qml/page/T_Awesome.qml
example/qml/window/HotloadWindow.qml
example/qml/window/MainWindow.qml
example/src/component/FileWatcher.cpp
example/src/component/FileWatcher.h
example/src/main.cpp
src/CMakeLists.txt
src/imports/FluentUI/Controls/FluRemoteLoader.qml

跟随主分支更新。
如果我有时间的话，会不定期处理该分支的更新。

Update to latest main.

---

example/qml/global/ItemsOriginal.qml
src/imports/FluentUI/Controls/FluDivider.qml
src/imports/FluentUI/Controls/FluNavigationView.qml
src/imports/FluentUI/Controls/FluPaneItemSeparator.qml

给FluPaneItemSeparator增加spacing和size属性

---

src/Qt6/imports/FluentUI/Controls/FluPivot.qml

optimize style for FluPivot

---

src/Qt5/imports/FluentUI/Controls/FluNavigationView.qml
src/Qt6/imports/FluentUI/Controls/FluNavigationView.qml

FluNavigationView 组件处于 `FluNavigationViewType.Compact` 模式时，鼠标移动到对应按钮上增加提示更加友好些。

FluNavigationView 组件增加了 tooltip 提示，交互更友好些。

---

.github/workflows/macos.yml
.github/workflows/ubuntu.yml
.github/workflows/windows-mingw.yml
.github/workflows/windows-qt5.yml
.github/workflows/windows.yml

1.去除掉一些不必要的重复字符
2.使用最新的虚拟机镜像（Qt 5由于要考虑在X86机型上运行，不修改）

Workflow: update.

---

example/qml-Qt6/page/T_ComboBox.qml
src/Qt6/imports/FluentUI/Controls/FluComboBox.qml

change style for ComboBox

---

CMakeLists.txt

CMakeLists: simplify code.

---

src/Qt5/imports/FluentUI/Controls/FluPagination.qml
src/Qt6/imports/FluentUI/Controls/FluPagination.qml

FluPagination.qml 添加自定义控件，通过header和footer属性添加控件

FluPagination.qml 添加自定义控件，通过header和footer属性添加控件

---

example/example_en_US.ts
example/example_zh_CN.ts
example/qml/page/T_TableView.qml

If the table doesn't have focus, a prompt will be given to the user. 
If the table has focus, a new row will be inserted before the focused item.

Add the functionality to insert new rows into the table

---

example/qml/page/T_GroupBox.qml
example/qml/page/T_InfoBar.qml
src/Qt5/imports/FluentUI/Controls/FluInfoBar.qml
src/Qt5/imports/FluentUI/Controls/FluRadioButtons.qml
src/Qt5/imports/FluentUI/Controls/FluWindow.qml
src/Qt6/imports/FluentUI/Controls/FluInfoBar.qml
src/Qt6/imports/FluentUI/Controls/FluRadioButtons.qml
src/Qt6/imports/FluentUI/Controls/FluWindow.qml

info提示语支持主动调用函数关闭，支持关闭所有info框的函数

info提示语支持主动调用函数关闭，支持关闭所有info框的函数

---

example/example_en_US.ts
example/example_zh_CN.ts
example/qml/page/T_TableView.qml

1. refactor: 使用三元表达式来选择头像的 source
2. docs: 更新翻译、修正 "The verification code is correct" 的中文翻译
> fix #543

refactor: 使用三元表达式来选择头像的 source (#543)

---

src/Qt5/imports/FluentUI/Controls/FluContentDialog.qml
src/Qt5/imports/FluentUI/Controls/FluInfoBar.qml
src/Qt5/imports/FluentUI/Controls/FluMultilineTextBox.qml
src/Qt5/imports/FluentUI/Controls/FluTimeline.qml
src/Qt5/imports/FluentUI/Controls/FluTour.qml
src/Qt6/imports/FluentUI/Controls/FluContentDialog.qml
src/Qt6/imports/FluentUI/Controls/FluInfoBar.qml
src/Qt6/imports/FluentUI/Controls/FluMultilineTextBox.qml
src/Qt6/imports/FluentUI/Controls/FluTimeline.qml
src/Qt6/imports/FluentUI/Controls/FluTour.qml

Maybe you have a valid reason to use Wrap Anywhere, but for english and french text, it is very unpleasant to read.
If this is a problem for Chinese, maybe a global variable to define the behavior?

Convert WrapAnywhere toWordWrap

---

example/example_en_US.ts
example/example_zh_CN.ts
example/qml/page/T_Expander.qml
src/Qt5/imports/FluentUI/Controls/FluExpander.qml
src/Qt6/imports/FluentUI/Controls/FluExpander.qml
src/fluentui_en_US.ts
src/fluentui_zh_CN.ts

- 使 FluExpander 支持自定义 header 的高度和内容
- 在 example 添加对应的使用例子

FluExpander 添加属性 headerHeight 和 headerDelegate

---

src/Qt5/imports/FluentUI/Controls/FluTableView.qml
src/Qt6/imports/FluentUI/Controls/FluTableView.qml

使用动态宽度时，宽度突变会出现表头、内容错位问题
修复前：
https://github.com/user-attachments/assets/9df5ef29-9cf5-4d70-b9fe-7b18bf885f7f
修复后：
https://github.com/user-attachments/assets/7800c23e-ad0a-47da-b48d-859ef9283d49

fix: 修复FluTableView错位问题

---

example/example_en_US.ts
example/example_zh_CN.ts
example/qml/page/T_Badge.qml
example/qml/page/T_TextBox.qml
src/Qt5/imports/FluentUI/Controls/FluAutoSuggestBox.qml
src/Qt5/imports/FluentUI/Controls/FluBadge.qml
src/Qt6/imports/FluentUI/Controls/FluAutoSuggestBox.qml
src/Qt6/imports/FluentUI/Controls/FluBadge.qml

1. FluAutoSuggestBox支持设置建议行数和行高以及pressed时显示建议
2. FluBadge支持设置max和position，支持字符串和数字显示

feat: 优化FluAutoSuggest和FluBadge

---

example/example_en_US.ts
example/example_zh_CN.ts
example/qml/page/T_Rectangle.qml
example/qml/page/T_TableView.qml
src/FluRectangle.cpp
src/FluRectangle.h
src/Qt5/imports/FluentUI/Controls/FluComboBox.qml
src/Qt5/imports/FluentUI/Controls/FluDatePicker.qml
src/Qt5/imports/FluentUI/Controls/FluMenuBarItem.qml
src/Qt5/imports/FluentUI/Controls/FluSpinBox.qml
src/Qt5/imports/FluentUI/Controls/FluTableView.qml
src/Qt5/imports/FluentUI/Controls/FluTextBoxBackground.qml
src/Qt5/imports/FluentUI/plugins.qmltypes
src/Qt6/imports/FluentUI/Controls/FluComboBox.qml
src/Qt6/imports/FluentUI/Controls/FluDatePicker.qml
src/Qt6/imports/FluentUI/Controls/FluMenuBarItem.qml
src/Qt6/imports/FluentUI/Controls/FluSpinBox.qml
src/Qt6/imports/FluentUI/Controls/FluTableView.qml
src/Qt6/imports/FluentUI/Controls/FluTextBoxBackground.qml

1. FluRectangle边框支持
2. FluDatePicker逻辑优化：修改月份时，若当前日存在于新的月份中则保持日不变，否则修改为新月份的最后一日，保持日期的接近性
3. FluComboBox、FluMenuBarItem、FluSpinBox、FluTextBoxBackground等控件用enabled替代disabled进行逻辑判断，因为disabled是一个扩展属性，不是强制使用的，实际使用时如果使用了enabled而不是disabled会导致disabled逻辑失效，因此代码逻辑判断层面还是使用enabled兼容性更好
4. FluTableView增加startRowIndex属性以支持分页数据场景下正确计算行序号。在实际应用中，表格数据分页展示时，行序号通常需根据分页的起始位置动态调整，因此应由外部定义行的起始序号

feat: 新增 FluRectangle 边框绘制、优化 FluDatePicker 月份切换逻辑、改进控件 enabled 属性兼容性及 FluTableView 分页行序号支持

---

example/example_en_US.ts
example/example_zh_CN.ts
example/qml/page/T_Rectangle.qml
example/qml/page/T_Tour.qml
example/qml/window/CrashWindow.qml
src/FluRectangle.cpp
src/FluRectangle.h
src/Qt5/imports/FluentUI/Controls/FluTour.qml
src/Qt5/imports/FluentUI/plugins.qmltypes
src/Qt6/imports/FluentUI/Controls/FluTour.qml

1. FluRectangle增加borderStyle和dashPattern以支持修改边框样式
2. FluTour改用Shape绘制以支持更改聚焦控件时的过渡动画，并增加指示器

feat: FluRectangle支持修改边框样式、FluTour增加指示器和动画效果

---

example/example.qrc
example/example_en_US.ts
example/example_zh_CN.ts
example/qml/component/CodeExpander.qml
example/qml/global/ItemsOriginal.qml
example/qml/page/T_Carousel.qml
example/qml/page/T_CheckBox.qml
example/qml/page/T_CountTimer.qml
example/qml/page/T_Icons.qml
example/qml/page/T_ParallaxView.qml
example/qml/window/MainWindow.qml
src/FluApp.cpp
src/FluApp.h
src/FluCountTimer.cpp
src/FluCountTimer.h
src/FluentUI.cpp
src/Qt5/imports/FluentUI/Controls/FluCarousel.qml
src/Qt5/imports/FluentUI/Controls/FluCheckBox.qml
src/Qt5/imports/FluentUI/Controls/FluParallaxView.qml
src/Qt5/imports/FluentUI/Controls/FluPinyin.qml
src/Qt5/imports/FluentUI/JS/PinyinPro.mjs
src/Qt5/imports/FluentUI/plugins.qmltypes
src/Qt5/imports/FluentUI/qmldir
src/Qt5/imports/fluentui.qrc
src/Qt6/imports/FluentUI/Controls/FluCarousel.qml
src/Qt6/imports/FluentUI/Controls/FluCheckBox.qml
src/Qt6/imports/FluentUI/Controls/FluParallaxView.qml
src/Qt6/imports/FluentUI/Controls/FluPinyin.qml
src/Qt6/imports/FluentUI/JS/PinyinPro.mjs
src/stdafx.h

1. 修复FluCarousel动态修改属性时显示错误，并优化示例展示
2. 新增计时器FluCountTimer，支持正计时、倒计时
3. FluPinyin增加单次从缓存匹配拼音函数hasPinyinMatch，优化合并部分重复逻辑
4. 新增视差视图FluParallaxView
https://github.com/user-attachments/assets/47a3c02e-7602-4bf8-a58f-d90164a015f2
5. 优化FluCheckBox过渡效果，补充三态复选框组合使用示例
https://github.com/user-attachments/assets/a5dd2d4c-46d7-474c-8383-9ea49c1707ea
closed #475

feat: 新增FluCountTimer、FluParallaxView，优化FluCheckBox、FluPinyin、FluCarousel
