zhuzichu520/FluentUI

example/CMakeLists.txt
因为 cmake 在 windows 下生成 dll 时会带有 lib 的前缀，导致 qml 在 import 库时无法找到，因此通过去掉前缀来修复这个问题
=> 🐛 修复 windows 下生成 dll 库带 linux 前缀导致查找不到控件

src/FluTheme.cpp
加入跟随系统自动切换深/亮色模式的功能。
在macOS 13.4 beta 2（Mac mini M2 2023）上测试通过。
演示视频：
https://user-images.githubusercontent.com/30333935/232242526-4aa4d9f0-5e56-47d8-8de7-79c9752b3dbc.mov
演示动图：
=> Add automatic dark color mode switching function.

example/T_Settings.qml, example/lang/En.cpp, example/lang/Lang.h, example/lang/Zh.cpp, src/FluTheme.cpp, src/FluTheme.h
例程中增加与系统同步开关；不再默认使夜间模式跟随系统。更新方法以消除代码编译时出现的所使用接口将被弃用的警告。
英文：
中文：
=> Add sync with system toggle switch and remove the deprecated warning.

example/T_Dialog.qml, example/page/MainPage.qml, src/controls/FluContentDialog.qml
以枚举类型为FluContentDialog提供三个按钮（FluContentDialog.NeutralButton、FluContentDialog.NegativeButton 、FluContentDialog.PositiveButton）的选择，并提供相应代码例子，为example程序窗口加入退出询问机制。
=> Imporve FluContentDialog and add relative example.

example/qml/page/T_Acrylic.qml, src/imports/FluentUI/Controls/FluAcrylic.qml
使用兼容Qt 6的模糊效果（FastBlur，根据QT 6官方文档，高斯模糊由于不兼容新的着色器而被废弃，使用FastBlur效果不能将效果实例作为需要模糊对象的子项）。
补充：macOS下测试没有GaussianBlur这一QML type。
=> Use Qt6 compatible blur effect.

src/imports/FluentUI/Controls/FluContentPage.qml, src/imports/FluentUI/Controls/FluNavigationView.qml, src/imports/FluentUI/Controls/FluScrollablePage.qml
模仿Android的Activity四种启动模式，为FluNavigationView增加三种页面加载模式：
+ Standard：标准模式，即每次点击标签按钮，FluNavigationView都将添加该页面的新实例，即便栈内已存在该页面实例。
+ SingleTop：栈顶复用模式，如果页面已是栈顶页面（即是FluNavigationView当前显示页面），将不再添加该页面的新实例（本想再加入一个类似Android的onNewIntent提示用的信号，但想想好像用不太上，就没加了）
+ SingleTask：栈内单例模式，栈内只存在相同页面的一个实例，假设用户共依次打开编号为1-5的界面，当处于5号界面，使用FluNavigationView切换至2号界面时，3-5号界面都将出栈并被销毁。
为解决 #92 #88 两个issues提供暂时的解决方法，个人认为SwipeView会是最合适的解决方案，之后有时间再实践一下。
=> Add PageMode for FluNavigationView.

src/FluTheme.cpp
=> Fix the _systemDark don't get system color while app first boot.

example/qml/window/MainWindow.qml, src/imports/FluentUI/Controls/FluContentDialog.qml
=> Add acrylic effect for FluContentDialog.

example/src/main.cpp, src/CMakeLists.txt
参见：
https://github.com/zhuzichu520/FluentUI/issues/127#issuecomment-1563724504
+ 多次尝试后，发现CMake中的
https://github.com/zhuzichu520/FluentUI/blob/a123dfbccf9136cede4ba085d231b54cf190646d/src/CMakeLists.txt#L74-L75
仅在MSVC上生效，在MinGW/GCC/Clang等编译器进行链接的时候，除非手动指定，否则不会链接这个生成的debug库。
+ framelesshelper中的`Global::Option::ForceHideWindowFrameBorder`选项仅在Windows上生效
=> 解决GCC类编译器链接的问题，修正framelesshelper中的flag

FluentUI-qt5-MSBuild.sln, example/example.vcxproj, example/example.vcxproj.filters, example/example.vcxproj.user, example/moc_debug_predefs.h.cbt, example/moc_release_predefs.h.cbt, src/fluentuiplugin.vcxproj, src/fluentuiplugin.vcxproj.filters, src/fluentuiplugin.vcxproj.user, src/moc_debug_predefs.h.cbt, src/moc_release_predefs.h.cbt
1.根目录添加2022的sln文件 src和example文件夹分别添加vcproj文件。
2.添加的vcproj文件最开头均有一个名为<QtDir>的项，同过设置该项改变编译使用的qt5版本，输入的路径为qt的bin lib include等文件夹所在的根目录 例如C:\Qt\Qt5.14.2\5.14.2\msvc2017_64 或者
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64或者C:\Qt\Qt5.15.2\5.15.2\msvc2019_64 上述版本测试均能编译通过且正常运行
3.将子工程的c++标准都升级成了17
4.程序编译后自动生成的中间文件以及Qt的Moc文件全在根目录下的generated文件夹中(该文件夹git ignored了)
5.vcproj文件中手打了各个文件的qt moc和rcc操作，因此不需要qt addin便可编译运行。
6.vcproj文件中的路径全都使用vs macro书写能够自适应正确的路径
7.没有结合FlamelessWindow相关代码
8.尝试把该工程中的QtDir设置为Qt6 发现能正常编译 但程序无法启动 会崩溃 (当前上传版本不支持Qt6编译，需要对引用lib中的Qt5和Qt6名字差异做版本区分 由于无法正常运行编译结果 所以没有上传)
=> ms-build相关文件上传

src/CMakeLists.txt
`qt_standard_project_setup`仅在 Qt 6.3以上版本有效。
=> Fix qt_standard_project_setup for Qt 6.2 and below.

example/CMakeLists.txt
在静态库环境下，缺少Qt::Svg库会导致加载Svg图片时出现`QML Image: Error decoding: XXX.svg: Unsupported image format`警告，此补丁解决这个问题。
=> Add Svg module to resolve unsupported image format error.

example/qml/page/T_Http.qml
1. fix the "FolderDialog is not a type" error in Qt 6.2.4 and below.
2. fix download error in macOS.
=> Fix the FolderDialog and macOS download bug.

example/qml/global/ItemsOriginal.qml
如下图所示，加入提示符号以提醒用户，避免出现无法区分不同Expander下同名项的问题（示例程序中不存在重名，若有用户直接照搬示例程序，可能出现类似情况）。
=> examlple: Make the items in searchbox more readable.

src/Qt5/imports/FluentUI/Controls/FluAcrylic.qml, src/Qt6/imports/FluentUI/Controls/FluAcrylic.qml
参考官方figma winui3设计稿，噪点图像占比为2%，不然看起来噪点太明显
=> 调整亚克力效果的噪点占比

example/src/AppInfo.h, example/src/helper/SettingsHelper.h, example/src/singleton.h, src/FluApp.h, src/FluColors.h, src/FluEventBus.h, src/FluNetwork.h, src/FluTextStyle.h, src/FluTheme.h, src/FluTools.h, src/FluViewModel.h, src/FluentUI.h, src/singleton.h
1.`SINGLETONG`宏定义应该是一个错误拼写，更正为`SINGLETON`
2.几个单例模式需要去除的函数Qt自带宏定义，可以简写为Q_DISABLE_COPY_MOVE
3.用Qt自带的线程锁代替标准库锁，以提高与Qt库的兼容性
=> Use more elegant singleton and fix spell bug.

src/Qt6/imports/FluentUI/Controls/FluSplitLayout.qml
FluSplitLayout handle's outside Rectangle use an implicitWidth/Height smaller than inside Rectangle.
this pr fix warning on qt 6.6.0:
QML Rectangle: Binding loop detected for property "height"
=> fix(FluSplitLayout): solve binding loop on qt 6.6.0

example/src/helper/Log.cpp, example/src/helper/Log.h, example/src/main.cpp
在vs2019下运行example,点击关闭在main函数退出之后会在函数messageHandler内部崩溃，所以添加Log::teardown函数，在main 函数调用，对应在main函数执行的Log::setup(...)
=> vs2019下example退出之后程序会崩溃

src/FluentUI.cpp
在Qt 6中，`:/qt/qml`本身就是默认`ImportPath`，因此无需再做些什么了。
=> static build: remove unused code.

example/CMakeLists.txt
In msys2 is possible install Qt5 + Qt6
In Qt6 
`lupdate` has name `lupdate-qt6.exe`
`lrelease` has name `lrelease-qt6.exe`
=> fix for msys2

src/Qt5/imports/FluentUI/Controls/FluCalendarPicker.qml, src/Qt6/imports/FluentUI/Controls/FluCalendarPicker.qml
=> 修复日历选择器夜间模式看不到星期的问题

src/Qt5/imports/FluentUI/Controls/FluComboBox.qml, src/Qt6/imports/FluentUI/Controls/FluComboBox.qml
Fixed bug with Popup topMargin because click is consumed by FluAppBar.
If the list of chooses use 100% of the window, the top part of the Popup is not clickable because the FluAppBar consume it for the double click resize of the window. So a simple solution is to set a bigger margin at the top (the size of the AppBar / Tiitle bar) to avoid the issue.
=> Fix FluComboBox click issue with AppBar

src/Qt5/imports/FluentUI/Controls/FluScrollablePage.qml, src/Qt6/imports/FluentUI/Controls/FluScrollablePage.qml
I use it in my application, I think it can be integrated into the main project. The autoResetScroll property, if true, resets the scroll to the top when StackView.onActivated is called. So the first time a page is viewed but also when the user goes back in the stack.
Not for all applications but in some cases it can be really useful.
=> Add property autoResetScroll to FluScrollablePage

example/example_en_US.ts, example/example_zh_CN.ts, example/qml/page/T_Buttons.qml, example/qml/page/T_Icons.qml, example/qml/page/T_Text.qml, src/Qt5/imports/FluentUI/Controls/FluCheckBox.qml, src/Qt5/imports/FluentUI/Controls/FluCopyableText.qml, src/Qt5/imports/FluentUI/Controls/FluIcon.qml, src/Qt5/imports/FluentUI/Controls/FluIconButton.qml, src/Qt5/imports/FluentUI/Controls/FluPivot.qml, src/Qt5/imports/FluentUI/Controls/FluRadioButton.qml, src/Qt5/imports/FluentUI/Controls/FluText.qml, src/Qt5/imports/FluentUI/Controls/FluToggleSwitch.qml, src/Qt6/imports/FluentUI/Controls/FluCheckBox.qml, src/Qt6/imports/FluentUI/Controls/FluCopyableText.qml, src/Qt6/imports/FluentUI/Controls/FluIcon.qml, src/Qt6/imports/FluentUI/Controls/FluIconButton.qml, src/Qt6/imports/FluentUI/Controls/FluPivot.qml, src/Qt6/imports/FluentUI/Controls/FluRadioButton.qml, src/Qt6/imports/FluentUI/Controls/FluText.qml, src/Qt6/imports/FluentUI/Controls/FluToggleSwitch.qml
根据 [WinUI 3 Gallery](https://github.com/microsoft/WinUI-Gallery)，Pivot 控件选中的 Tab 应该高亮
根据 [WinUI 3 Gallery](https://github.com/microsoft/WinUI-Gallery)，上述控件禁用后文本或者图标不该高亮
=> 修复部分控件的错误高亮问题

src/Qt5/imports/FluentUI/Controls/FluNavigationView.qml, src/Qt6/imports/FluentUI/Controls/FluNavigationView.qml
Fix FluNavigationView noStackPush to verify if an argument is passed. If true, it is better to set the page has a new one in order to update it with the arguments.
For example, in my app, I have the following pages: 
- List.qml
- Form.qml
The list doesn't have arguments, so a click on the navigation to the list doesn't need to re-render the page. But for the Form.qml, I have an id has parameter. If the id change, it is not the same data in the form, so I need to re-render like a new one. In my use case, the search box list all the clients and I can switch between them from this input, without the PR, it doesn't work because the code consider it is the same page even if the arguments are different.
=> Fix FluNavigationView noStackPush

.github/workflows/ubuntu.yml
GitHub Action 打包的 example_x.x.x_ubuntu-latest_Qt6.6.2.AppImage 缺少语言包，切换中文重启后还是显示英文。
修复前：
修复后：
=> fix(ci): 修复 GitHub Action 打包的 AppImage 语言切换无效

src/FluTools.cpp
1. 在 Ubuntu 中设置 `FluTheme.blurBehindWindowEnabled=true` 时报错 Segmentation Fault，此错误应该在非 UOS 的 Linux 下会出现，修复此问题
2. 让 Ubuntu gnome 桌面亚克力背景生效
=> fix: 修复了在 Ubuntu 中启用亚克力效果无效且导致程序崩溃的问题

src/Qt5/imports/FluentUI/Controls/FluColorPicker.qml, src/Qt6/imports/FluentUI/Controls/FluColorPicker.qml
- 修复了 FluColorPicker 打开时滑块与 RGBA/HEX 数值未正确匹配当前颜色的问题
前：
https://github.com/user-attachments/assets/99d86f34-bbd2-4299-8a7a-a0e6c68cbfcd
后：
https://github.com/user-attachments/assets/38a995c2-9302-4b7a-b7b3-82890b54d8d9
- 修复了 FluColorPicker 设置 HEX 值时，RGBA 数值未同步更新的问题
- 修复了 FluColorPicker HEX 输入框只能接受大写 A-F 字符的问题
前：
https://github.com/user-attachments/assets/c05a5b0b-56e8-4abc-8c5d-86ba692e22ff
后：
https://github.com/user-attachments/assets/7159456c-ee64-4c3b-856d-9697e926c816
=> 修复 FluColorPicker 存在的颜色同步与输入问题

src/Qt5/imports/FluentUI/Controls/FluPivot.qml, src/Qt6/imports/FluentUI/Controls/FluPivot.qml
修复了在 `FluTheme.animationEnabled = false` 时，从文字较少的 title 切换到文字较多的 title 时，下划线仍然存在尺寸变化动画的问题。
前：
https://github.com/user-attachments/assets/a59e9d0b-87d4-421c-87d9-8f3f7355aab5
后：
https://github.com/user-attachments/assets/3455a8e2-620a-4d46-9953-ece649427609
=> 修复FluPivot 切换选中项目时标题下划线动画未能完全关闭的问题

example/example_en_US.ts, example/example_zh_CN.ts, example/qml/page/T_Acrylic.qml, example/qml/page/T_BreadcrumbBar.qml, example/qml/page/T_Captcha.qml, example/qml/page/T_ComboBox.qml, example/qml/page/T_InfoBar.qml, example/qml/page/T_QRCode.qml, example/qml/page/T_SplitLayout.qml, example/qml/page/T_StatusLayout.qml, example/qml/page/T_TabView.qml, example/qml/page/T_Theme.qml, example/qml/page/T_Timeline.qml, example/qml/page/T_TreeView.qml, example/qml/page/T_Typography.qml, example/qml/page/T_Watermark.qml
add some chinese translation in example
=> fix: add some chinese translation in example

src/Qt5/imports/FluentUI/Controls/FluCarousel.qml, src/Qt5/imports/FluentUI/Controls/FluProgressBar.qml, src/Qt6/imports/FluentUI/Controls/FluCarousel.qml, src/Qt6/imports/FluentUI/Controls/FluProgressBar.qml
1. 修复 #563，禁止自动轮播后，手动翻页会触发自动轮播的问题
修复前：
https://github.com/user-attachments/assets/06266650-f937-4e10-b460-30a394f53c44
2. 修复第1个问题后，发现手动翻页不能无限轮播，进一步做修复
修复前：
https://github.com/user-attachments/assets/5d17a975-cdfa-4210-a83e-222a3f932740
完整修复后：
https://github.com/user-attachments/assets/466c6484-e8e3-45d2-b12f-50f9999e471b
fixed #563
=> 修复FluCarousel手动翻页的问题

.vscode/settings.json, example/qml/page/T_Pivot.qml
修复Pivot的示例代码错误，具体为删除FluPivotItem后面的冒号，将FluPivotItem的text属性改为title属性
=> 修复Pivot的示例代码错误

example/example_en_US.ts, example/example_zh_CN.ts, example/qml/page/T_Buttons.qml
优化 example 中加载按钮页面交互效果
修改前：
**修改后**
**英文部分**
=> fix: 优化示例中加载按钮交互效果

src/FluTreeModel.cpp, src/Qt5/imports/FluentUI/Controls/FluTreeView.qml, src/Qt6/imports/FluentUI/Controls/FluTreeView.qml
多次调用setDataSource会存在内存泄漏，直到FluTreeModel销毁，因为子节点的父对象是FluTreeModel而不是_root，而_dataSource.clear()并不会销毁子节点对象，需要qDeleteAll(_dataSource)，或将子节点父对象设为_root
修复前：
https://github.com/user-attachments/assets/d42c44eb-0d00-4d90-a7f4-1679c62e2f8e
修复后：
https://github.com/user-attachments/assets/46d7eef4-84c6-487e-aa35-3bf1d30b0097
=> 修复FluTreeModel::setDataSource内存泄漏问题
